---
title: "Ejemplo final"
author: "Nicolás Barceló"
date: "15/12/2020"
output: html_document
---

# Ejemplo final

## Juntar color de ojos y pelo sin distinguir por sexo

```{r}
ftable(HairEyeColor)
male <- HairEyeColor[,,"Male"]
female <- HairEyeColor[,,"Female"]
data <- as.table(male+female)
data
```

## Manipulación de datos

```{r}
dimnames(data) = list(
  Pelo = c("Negro", "Marron", "Pelirrojo", "Rubio"),
  Ojos = c("Marrones", "Azules", "Pardos", "Verdes")
)
data
```
## Diagrama de mosaico

```{r}
plot(data, col = c("lightblue"), main = "Diagrama de Mosaico")
```

## Datos numéricos

```{r}
# Numero total de individuos
sum(data)
```

```{r}
colSums(data)
rowSums(data)
round(prop.table(colSums(data)),3)
round(prop.table(rowSums(data)),3)
```
## Diagramas de barras

```{r}
barplot(prop.table(colSums(data)), ylim = c(0, 0.4),
        main = "Frecuencias relativas de color de ojos",
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"))

barplot(prop.table(rowSums(data)), ylim = c(0, 0.5),
        main = "Frecuencias relativas de color de cabello",
        col = c("black", "brown", "red", "yellow"))
```

## Frecuencias relativas globales y marginales

```{r}
round(prop.table(data),3)
round(prop.table(data, margin = 1),3)
round(prop.table(data, margin = 2),3)

barplot(prop.table(data, margin = 1), beside = TRUE,
        legend.text = TRUE, ylim = c(0, 0.8),
        col = c("black", "burlywood4", "red", "gold"),
        main = "Frecuencias realtivas del color de pelo\npara cada color de ojos")

barplot(t(prop.table(data, margin = 2)), beside = TRUE,
        legend.text = TRUE, ylim = c(0, 0.6),
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"),
        main = "Frecuencias realtivas del color de ojos\npara cada color de pelo")
```

