---
title: "Carga de dataframes"
author: "Nicolás Barceló"
date: "26/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga de ficheros local
```{r}
df = read.table("../../data/bulls.dat", 
                header = FALSE,
                col.names = c("breed", "sale_price", "shoulder",
                          "fat_free", "percent_ff", "frame_scale",
                          "bad_fat", "sale_height", "sale_height"))
head(df)
str(df)
```


## Factores en un DF
```{r}
df3 = read.table("../../data/olive.txt",
                 header = TRUE,
                 dec = ".")
str(df3)
```
## Construyendo data frames

```{r}
gender = c("H", "M", "M", "M", "H")
age =    c( 23,   45, 20,  30,  18)
family = c(  2,    3,  4,   2,   5)

df5 = data.frame(genero = gender,
                 edad = age,
                 familia = family,
                 stringsAsFactors = TRUE)
row.names(df5) = c("P1", "P2", "P3", "P4", "P5")
df5
str(df5)
```














