---
title: "Gráficos"
author: "Nicolás Barceló"
date: "18/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos con la función `plot`

```{r primer_plot, fig.cap="Gráfico básico explicando el uso del plot", fig.align="center"}
x = c(2,6,4,9,-1)
y = c(1,8,4,-2,4)
plot(x,y)
```

Si no incorporamos vector `y`, `R` nos va a tomar el parámetro `x` como si fuese el vector de datos `y`: `plot(1:n, x)`

```{r}
plot(2^(1:6))
```

Si queremos representar una función $f(x)$:

```{r}
f <- function(x) {sqrt(x)}
plot(f)
```


## Parámetros

```{r echo=FALSE, fig.align='center'}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
fib
par(mfrow = c(1,2))
plot(fib, xlab = "n", ylab = expression(F[n]),
     main = "Sucesión de Fibonacci", pch=20, cex=4, col = "powderblue",
     log = "xy")
plot(fib, xlab = "n", ylab = expression(F[n]),
     main = "Sucesión de Fibonacci", pch=20, cex=4, col = "powderblue",
     log = "y")
par(mfrow = c(1,1))
```
```{r}
plot(n, fib, pch = 21, col = "red", bg = "yellow", cex = 1.2,
     main = "Fibbonaci",
     type = "o", lty = "dotted")
```

## Como añadir elementos a un gráfico
```{r}
f <- function(x) {
        x^2-2*x + sqrt(abs(x))
}
plot(f, xlim = c(-3,3))
points(0,0, pch = 19)
points(-3:3, (-3:3)^2, col = "blue")
abline(2, 3, lty = "dashed", col = "red")
abline(v = 2, lty = "dotted", col = "green")
abline(h = 5, lty = "dashed", col = "grey")
```

```{r}
f <- function(x) {x^2}
plot(f, xlim = c(-3,3), col = "red", lwd = 2, ylab = expression(y^2),
     xlab = "x")
abline(h=0:9, v = -3:3, lty="dotted", col="grey")
```
```{r}
plot(tan, xlim = c(-pi, pi), ylim = c(-5,5))
abline(v = c(-pi/2, pi/2), col = "red")
```

```{r}
plot(0,0)
text(0,0, labels = "debajo", pos = 1)
```

```{r}
f <- function(x) {x^2}
plot(f, 
     xlim = c(-3, 3), 
     ylim = c(-10, 10))
points(-3:3, 
       f(-3:3), 
       pch = 19)
lines(-3:3, 
      f(-3:3), 
      lwd = 2, 
      lty = "dotted", 
      col = "red")
curve(x^3, 
      lty = "dashed", 
      col = "blue", 
      add = TRUE)
curve(x^4, 
      lty = "dashed", 
      col = "orangered", 
      add = TRUE)
legend("bottomright", 
       legend = c(expression(x^2), expression(x^3), expression(x^4)), 
       lw = 2, 
       col = c("red", "blue", "orangered"), 
       lty = c("dotted", "dashed", "dashed"))
```

